DemoDotNet/Controllers/ProcessController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DemoDotNet.Models;
using Google.Apis.Auth.OAuth2;
using Microsoft.Extensions.Configuration;

namespace DemoDotNet.Controllers
{

    public class ProcessController : Controller
    {
        private readonly ILogger<ProcessController> _logger;
        private readonly Services.ZeebeClientProvider _zeebeClientProvider;
        private readonly IConfiguration _configuration;

        public ProcessController(ILogger<ProcessController> logger, Services.ZeebeClientProvider zeebeClientProvider, IConfiguration configuration)
        {
            _logger = logger;
            _zeebeClientProvider = zeebeClientProvider;
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> GetClusterTopology()
        {
            // Get cluster topology
            var topology = await _zeebeClientProvider.GetZeebeClient().TopologyRequest().Send();

            Console.WriteLine("Cluster connected: " + topology);

            return new JsonResult(new { topology = topology });
        }

        [HttpPost]
        public async Task<JsonResult> DeployProcess([FromQuery] string processName)
        {
            var processPath = _configuration.GetValue<string>("ResourcePath");
            var demoProcessPath = $"{processPath}/{processName}.bpmn";

            var deployResponse = await _zeebeClientProvider.GetZeebeClient().NewDeployCommand()
                .AddResourceFile(demoProcessPath)
                .Send();

            var processDefinitionKey = deployResponse.Processes[0].ProcessDefinitionKey;

            return new JsonResult(new { processDefinitionKey = processDefinitionKey });
        }

        [HttpPost]
        public async Task<JsonResult> CreateProcessInstance([FromQuery] string processId)
        {
            //sample - sample process with some dummy variables
            var processInstanceVariables = "{\"sampleData1\":\"12424\", \"sampleData2\":\"Applicant1\" }";
            var processInstance = await _zeebeClientProvider.GetZeebeClient()
                .NewCreateProcessInstanceCommand()
                .BpmnProcessId(processId)
                .LatestVersion()
                .Variables(processInstanceVariables)
                .Send();


            //Refer below - setting new procecss variables
            await _zeebeClientProvider.GetZeebeClient().NewSetVariablesCommand(processInstance.ProcessInstanceKey).Variables("{\"email\":\"email@sample.com\" }").Local().Send();

            return new JsonResult(new { ProcessInstanceKey = processInstance.ProcessInstanceKey });
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        
    }
}

DemoDotNet/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DemoDotNet.Models;
using Google.Apis.Auth.OAuth2;
using Zeebe.Client.Impl.Builder;
using Zeebe.Client.Impl.Responses;
using Zeebe.Client;
using static DemoDotNet.Models.Models;
using System.Collections;
using DemoDotNet.Services;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Configuration;
using GraphQL;

namespace DemoDotNet.Controllers
{  

    public class TaskController : Controller
    {       
        private readonly ILogger<TaskController> _logger;
        private readonly TaskListService _taskListService;

        public TaskController(ILogger<TaskController> logger, TaskListService taskListService)
        {
            _logger = logger;
            _taskListService = taskListService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> GetAllTasks()
        {
            var alltasks = await _taskListService.FetchAllTasks();

            return new JsonResult(new { tasks = alltasks });
        }

        [HttpGet]
        public async Task<JsonResult> GetOpenTasks()
        {
            var alltasks = await _taskListService.FetchAllTasks();            

            return new JsonResult(new { tasks = alltasks.Where(i=>i.assignee is null).ToList() });
        }

        [HttpGet]
        public async Task<JsonResult> GetTask(string taskId)
        {            
            return new JsonResult(new { task = await _taskListService.GetTask(taskId) });       
        }

        [HttpGet]
        public async Task<JsonResult> GetTaskByProcessInstanceId([FromQuery] string processInstanceId)
        {
            var task = await _taskListService.GetTaskByProcessInstanceId(processInstanceId);

            return new JsonResult(new {task });

        }

        [HttpGet]
        public async Task<JsonResult> GetTasksByUser([FromQuery] string user)
        {
            var tasks = await _taskListService.GetTasksByUser(user);
            return new JsonResult(new { tasks });
        }

        [HttpGet]
        public async Task<JsonResult> GetCompletedTasks([FromQuery] string user)
        {
            var tasks = await _taskListService.GetCompletedTasks(user);
            return new JsonResult(new { tasks });
        }

        [HttpPost]
        public  async Task<JsonResult> ClaimTask([FromQuery]string taskId, [FromQuery] string user)
        {
            var task = await _taskListService.ClaimTask(taskId, user);
            return new JsonResult(new { claimedTask = task });
        }


        [HttpPost]
        public async Task<JsonResult> UnClaimTask([FromQuery] string taskId)
        {
            var task = await _taskListService.UnClaimTask(taskId);
            return new JsonResult(new { claimedTask = task});
        }

        [HttpPost]
        public async Task<JsonResult> CompleteTask([FromQuery] string taskId)
        {
            var task = await _taskListService.CompleteTask(taskId);
            return new JsonResult(new { claimedTask = task });
        }

        
                
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }        
    }
}

DemoDotNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoDotNet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <img height="80px" src=".\Secondary-Logo_Rounded-Orange.png" width="80px">               
                    <a style="padding-left: 25px;" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo DotNet Clients</a>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Process" asp-action="Index">Processes</a>
                        </li>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Index">Tasks</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DemoDotNet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>